export const COURSE_REQUEST = "COURSE_REQUEST";
export const COURSE_SUCCESS = "COURSE_SUCCESS";
export const COURSE_FAILURE = "COURSE_FAILURE";

export const ADD_COURSE_REQUEST = "ADD_COURSE_REQUEST";
export const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS";
export const ADD_COURSE_FAILURE = "ADD_COURSE_FAILURE";
